OPENQASM 3.0;
include "stdgates.inc";
gate _ccircuit_163 _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4 {
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_4, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_1;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_0, _gate_q_3;
  cx _gate_q_0, _gate_q_4;
}
gate _ccircuit_171 _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4 {
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_4, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_1;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_0, _gate_q_3;
  cx _gate_q_0, _gate_q_4;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_4, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_1;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_0, _gate_q_3;
  cx _gate_q_0, _gate_q_4;
}
gate _ccircuit_179 _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4 {
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_4, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_1;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_0, _gate_q_3;
  cx _gate_q_0, _gate_q_4;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_4, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_1;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_0, _gate_q_3;
  cx _gate_q_0, _gate_q_4;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_4, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_1;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_0, _gate_q_3;
  cx _gate_q_0, _gate_q_4;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_4, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_1;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_0, _gate_q_3;
  cx _gate_q_0, _gate_q_4;
}
gate _ccircuit_187 _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4 {
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_4, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_1;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_0, _gate_q_3;
  cx _gate_q_0, _gate_q_4;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_4, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_1;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_0, _gate_q_3;
  cx _gate_q_0, _gate_q_4;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_4, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_1;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_0, _gate_q_3;
  cx _gate_q_0, _gate_q_4;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_4, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_1;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_0, _gate_q_3;
  cx _gate_q_0, _gate_q_4;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_4, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_1;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_0, _gate_q_3;
  cx _gate_q_0, _gate_q_4;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_4, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_1;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_0, _gate_q_3;
  cx _gate_q_0, _gate_q_4;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_4, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_1;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_0, _gate_q_3;
  cx _gate_q_0, _gate_q_4;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_4, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_4;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_3;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_1;
  ccx _gate_q_0, _gate_q_1, _gate_q_2;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_0, _gate_q_3;
  cx _gate_q_0, _gate_q_4;
}
qubit[4] count;
qubit[4] work;
h count[0];
h count[1];
h count[2];
h count[3];
x work[0];
_ccircuit_163 count[0], work[0], work[1], work[2], work[3];
_ccircuit_171 count[1], work[0], work[1], work[2], work[3];
_ccircuit_179 count[2], work[0], work[1], work[2], work[3];
_ccircuit_187 count[3], work[0], work[1], work[2], work[3];
swap count[0], count[3];
swap count[1], count[2];
h count[0];
cp(-pi/2) count[0], count[1];
h count[1];
cp(-pi/4) count[0], count[2];
cp(-pi/2) count[1], count[2];
h count[2];
cp(-pi/8) count[0], count[3];
cp(-pi/4) count[1], count[3];
cp(-pi/2) count[2], count[3];
h count[3];


//N = 15, a = 7